### ISSUE TITLE
Error on mha_read_volume

### ISSUE THREAD

**Issue by ShibaPrasad** [FNNDSC/matlab#3]
Hi 

I am trying to read the .mhd file using the code

info = mha_read_header('/var/tmp/Shiba/H-17192/scans/H-17192_V1_INSP.mhd')
V = mha_read_volume(info)
imshow(squeeze(V(:,:,round(end/2))),[]);

and getting below error:

Error using fopen
First input must be a file name or a file identifier.

Error in mha_read_volume (line 28)
        fid=fopen(info.Filename','rb','ieee-le');

Error in test (line 28)
V = mha_read_volume(info)

**Comment by ShibaPrasad** [comment]
**I am able to solve the above issue. But getting another issue like below:**

Error using mha_read_volume>zlib_decompress (line 86)
Java exception occurred:
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at java.io.ByteArrayOutputStream.grow(Unknown Source)
	at java.io.ByteArrayOutputStream.ensureCapacity(Unknown Source)
	at java.io.ByteArrayOutputStream.write(Unknown Source)
	at com.mathworks.mlwidgets.io.InterruptibleStreamCopier.copyStream(InterruptibleStreamCopier.java:74)
	at com.mathworks.mlwidgets.io.InterruptibleStreamCopier.copyStream(InterruptibleStreamCopier.java:51)

Error in mha_read_volume (line 74)
        V = zlib_decompress(Z,DataType);

Error in test (line 29)
V = mha_read_volume(info)

**Comment by ShibaPrasad** [comment]
Solved

**Comment by MarwaSalhi** [comment]
Hi ShibaPrasad,
How did you solve the "Error using fopen", please?

**Comment by rkZ-10** [comment]
How did you solve the error:

Error using fopen
First input must be a file name or a file identifier.

Error in mha_read_volume (line 28)
fid=fopen(info.Filename','rb','ieee-le');

Error in test (line 28)
V = mha_read_volume(info)

**Comment by MarwaSalhi** [comment]
Hello,
You have to eliminate single quotes(') from the file name.

switch(info.ByteOrder(1))
    case ('true')
        fid=fopen(info.Filename','rb','ieee-be');
    otherwise
        fid=fopen(info.Filename','rb','ieee-le');
end
________________________________
De : rkZ-10 <notifications@github.com>
Envoyé : dimanche 15 mars 2020 10:30
À : FNNDSC/matlab <matlab@noreply.github.com>
Cc : Marwa SALHI <maroua.salhi@supcom.tn>; Comment <comment@noreply.github.com>
Objet : Re: [FNNDSC/matlab] Error on mha_read_volume (#3)


How did you solve the error:

Error using fopen
First input must be a file name or a file identifier.

Error in mha_read_volume (line 28)
fid=fopen(info.Filename','rb','ieee-le');

Error in test (line 28)
V = mha_read_volume(info)

**Comment by rkZ-10** [comment]
@MarwaSalhi . Thanks
